#!/bin/bash
svg=false
args=()
for arg in "$@"; do
  if [ "$arg" = "-s" ]; then
    svg=true
  else
    args+=("$arg")
  fi
done
set -- "${args[@]}"

if [ $# -ne 2 ]; then
  echo "Usage: $0 [-s] <filename> <float|double>"
  exit 1
fi

if [ "$2" != "float" ] && [ "$2" != "double" ]; then
  echo "Second argument must be 'float' or 'double'"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

precision_flag=""
if [ "$1" = "float" ]; then
    precision_flag="-single"
elif [ "$1" = "double" ]; then
    precision_flag="-double"
fi

filepath="$1"
pathname=$(dirname "$filepath")
filename=$(basename "$filepath") 
name="${filename%.*}"
ext="${filename##*.}"
outfile="${name}_faustproc.hpp"

echo "Generating:    $outfile ..."
faust -nvi -vec -vs 4 $precision_flag -lang cpp -a $SCRIPT_DIR/faust-hpp.cpp -cn $name $filepath -o $pathname/$outfile

# Modify the autogenerated code
sed -i '/#define FAUSTFLOAT \(float\|double\)/d; /#ifndef FAUSTFLOAT/{N;N;/#ifndef FAUSTFLOAT\n#define FAUSTFLOAT \(float\|double\)\n#endif/d}' $pathname/$outfile
sed -i 's/^class \(.*\) final : public dsp {/template <typename FAUSTFLOAT>\nclass \1 {/' $pathname/$outfile
sed -i '/static void classInit(int sample_rate) {/{N; s/static void classInit(int sample_rate) {\n[[:space:]]*}/static void classInit(int \/*sample_rate*\/) {}/}' $pathname/$outfile
echo "Generating:    $outfile complete."

if [ "$svg" = true ]; then
  echo "Generating:    ${name}-svg/process.svg"
  faust2svg $filepath
fi
